### ISSUE TITLE
Find a more dynamic way of setting the order detail background container size

### ISSUE THREAD

**Issue by oshalygin** [oshalygin/mdjs#149]
Currently there is a hardcoded height value of `100rem`.  This needs to be more fluid, the problem is that there is a crapton of absolute/relative positioning which borks everything.

```css

.order-detail-background-container {
  box-sizing: border-box;
  position: relative;
  height: 100rem;
  width: 100%;
  background-image: linear-gradient(bottom, var(--typhoon) 80%, var(--darkBlue) 20%);
}
```
